name: Android APK Build

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        default: 'World'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gradle build
        run: ./gradlew assembleA52Debug assembleG400Debug

      - name: Upload APKs
        uses: actions/upload-artifact@v3
        with:
          name: built-apks
          path: app/build/outputs/apk/**/**/*.apk

      - name: Send greeting
        run: echo "Hello ${{ inputs.name }}"
